### ISSUE TITLE
Fix travis build status link in README

### ISSUE THREAD

**Issue by wobh** [exercism/common-lisp#160]
That is all.

**Comment by verdammelt** [comment]
> That is all.

Sorry - but can you add a bit more detail here? Do you mean that the badge in the readme is showing that master is GREEN but a branch is RED? (and thus (you are saying) should not show GREEN?)

**Comment by wobh** [comment]
OOPS it was just me.

**Comment by verdammelt** [comment]
Wow that was *really* low-hanging fruit :)
