### ISSUE TITLE
Decide which exercises are "core" exercises.

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#165]
See https://github.com/exercism/common-lisp/pull/164

**Comment by verdammelt** [comment]
*casts resurrect-issue*

**Comment by serialhex** [comment]
It doesn't seem like there is a "global" set of core & depends-on exercises (if there is, I haven't seen it) but looking at the list of exercises, I think the following should be a bare-minimum:

- [x] Hello World
- [x] Bob
- [ ] Sum of Multiples
- [ ] Accumulate
- [x] Beer Song
- [x] Sieve


This is just from a cursory glance and it's just my own opinion.  There are probably others we should include also, but I'm just trying to get the conversation (actually) started.

**Comment by verdammelt** [comment]
@serialhex What is the significance of checked and unchecked boxes in the above list?

(Also - thanks for jumping in and trying to move this issue forward.)

**Comment by serialhex** [comment]
The checked boxes are exercises that have been implemented, the unchecked have not yet been implemented on the track yet.  That's all.

You're probably more familiar with all this than I am, are there any exercises you think are core?  Maybe I should see what the C# guys have and steal their list... :smiling_imp:

**Comment by verdammelt** [comment]
RE: ` are there any exercises you think are core?` 
Have you noticed how *much* activity on this issue there has been before you showed up? :)

I'm trying to get back more time for this track.

Off the top of my head I might say that hamming & leap are pretty core (mapping/reducing/looping & conditional expressions). Bob for its use of `cond`. Beer Song only if we are saying the `format` trick makes it "core".

Maybe we can start with that?

**Comment by serialhex** [comment]
Ok, cool, so thus far we have:

- Hello World (basic, all languages)
- Bob (cond)
- Sum of Multiples (numbers, not implemented yet)
- Accumulate (not here b/c too easy? what if we say no mapcar??)
- Beer Song (format)
- Sieve (numbers, looping/recursion)
- Hamming (mapping w/ multiple lists)
- Leap (mapping & some numbers)

made new PR #181 with these changes (I can always add if someone thinks there might be more to add soonish)

**Comment by verdammelt** [comment]
Decided to merge that PR (thanks!). We can add more core exercises later as we continue.

**Comment by verdammelt** [comment]
@serialhex Do you think this issue could be closed now that your PR is merged? I figure when new exercises are added we need to ask the question: Is this core?

**Comment by serialhex** [comment]
@verdammelt Yes I think it can be closed.  At least we have a few and can build from there!
