### ISSUE TITLE
Find a solution to the Travis problems!

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#179]

**Comment by serialhex** [comment]
Warning: I've never used a CI server, so I may not know WTF I'm talking about and be way off base.

It seems like Travis uses Debian Linux (or at least the apt package manager) so why not use the packages provided in apt for the versions that are available?  That would be sbcl, ecl, clisp, and cmucl.  Personally I've never been able to *build* sbcl, no matter how many times I've tried.  If there are binary packages available in Roswell, then why not use those?

You commented out the `#- LISP=sbcl-bin` in the .travis.yml file so we don't run both sbcl & sbcl-bin, from what I've seen it's the build process that's failing, maybe switch to the binary package?

**Comment by verdammelt** [comment]
So not entirely a *solution* but switching it back to sbcl-bin causes the build to be green.

I think I commented it out and used sbcl instead *at the time* because sbcl-bin was a much older version... so building sbcl seemed reasonable. But thinking now... our excercises should not need up-to-the-moment versions of implementations.

**Comment by serialhex** [comment]
Yeah, the Common Lisp standard is what, 30+ years old now?  (yeah, 23 years for ANSI CL, and 33 for CL in general)  People should *technically* be able to load up an old version of MCL on their Power Mac G4 and have everything run fine... :stuck_out_tongue_winking_eye:
