### ISSUE TITLE
Ensure Common Lisp track is ready for v2 launch

### ISSUE THREAD

**Issue by kytrinyx** [exercism/common-lisp#208]
There are a number of things we're going to want to check before the v2 site goes live. There are notes below that flesh out all the checklist items.

- [x] The track has a page on the v2 site: https://v2.exercism.io/tracks/common-lisp
- [x] The track page has a short description under the name (not starting with `TODO`)
- [x] The "About" section is a friendly, colloquial, compelling introduction
- [x] The "About" section follows the formatting guidelines
- [x] The code example gives a good taste of the language and fits within the boundaries of the background image
- [x] There are exercises marked as `core`
- [x] Exercises have rough estimates of difficulty
- [x] Exercises have topics associated with them
- [x] The first exercise is `auto_approve: true`

## Track landing page

The v2 site has a landing page for each track, which should make people want to join it. If the track page is missing, ping `@kytrinyx` to get it added.

### Blurb
If the header of the page starts with `TODO`, then submit a pull request to https://github.com/exercism/common-lisp/blob/master/config.json with a `blurb` key.  Remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### About section
If the "About" section feels a bit dry, then submit a pull request to https://github.com/exercism/common-lisp/blob/master/docs/ABOUT.md with suggested tweaks.

#### Formatting guidelines
In order to work well with the design of the new site, we're restricting the formatting of the `ABOUT.md`. It can use:

* Bold
* Italics
* Links
* Bullet lists
* Number lists

Additionally:

* Each sentence should be on its own line
* Paragraphs should be separated by an empty line
* Explicit `<br/>` can be used to split a paragraph into lines without spacing between them, however this is discouraged.

### Code example
If the code example is too short or too wide or too long or too uninteresting, submit a pull request to https://github.com/exercism/common-lisp/blob/master/docs/SNIPPET.txt with a suggested replacement.

## Exercise metadata
Where the v1 site has a long, linear list of exercises, the v2 site has organized exercises into a small set of required exercises ("core").

If you update the track config, remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### Topic and difficulty
Core exercises unlock optional additional exercises, which can be filtered by topic an difficulty, however that will only work if we add topics and difficulties to the exercises in the track config, which is in https://github.com/exercism/common-lisp/blob/master/config.json

### Auto-approval
We've currently made any hello-world exercises auto-approved in the backend of v2. This means that you don't need mentor approval in order to move forward when you've completed that exercise.

Not all tracks have a hello-world, and some tracks might want to auto approve other (or additional) exercises.

## Track mentors
There are no bullet points for this one :)

As we move towards the launch of the new version of Exercism we are going to be ramping up on actively recruiting people to help provide feedback. Our goal is to get to 100%: everyone who submits a solution and wants feedback should get feedback. Good feedback.

If you're interested in helping mentor the track, check out http://mentoring.exercism.io/

#
When all of the boxes are ticked off, please close the issue.

Tracking progress in https://github.com/exercism/meta/issues/104

**Comment by verdammelt** [comment]
Thanks @kytrinyx !

**Comment by wobh** [comment]
For the blurb we might be able to draw inspiration from https://en.wikiquote.org/wiki/Lisp_(programming_language)

I like, "A programmable programming language" after Foderaro.

**Comment by jackhughesweb** [comment]
Things that can be checked off:
> The track page has a short description under the name (not starting with TODO)
> The "About" section is a friendly, colloquial, compelling introduction
> The "About" section follows the formatting guidelines
> There are exercises marked as core
> Exercises have topics associated with them
> The first exercise is auto_approve: true

Things that still need completing:
> The code snippet is too wide and too tall for the area it is displayed in (see https://v2.exercism.io/tracks/common-lisp)
> Need to add a blurb
> Need to add difficulties to exercises
> Need to add `unlocked_by` to non-core exercises

**Comment by verdammelt** [comment]
Thanks @jackhughesweb for going through these. I am going to set aside some time in the next two days to hopefully address these issues.

Thanks again for helping me with this work.

**Comment by wobh** [comment]
I'm certain we can write a smaller code snippet dropping the package setup and the docstring also moving the test parameter into the body, but it would be less "well-formed". If the purpose of the snippet is to be small enough to fit in the little window we could do this:

```lisp
(defun distance (str1 str2)
  (when (= (length str1) (length str2))
    (count nil
           (map 'list #'char= str1 str2))))
```

And that's probably enough to go on.

**Comment by verdammelt** [comment]
@wobh I think I'd like to keep the doc string. Maybe this will work?

```
(defun distance (str1 str2
                 &key (test #'char=))
  "Number of positional differences in
   two equal length strings."
  (when (= (length str1) (length str2))
    (count nil
           (map 'list test str1 str2))))
```

**Comment by verdammelt** [comment]
@kytrinyx how soon after making a change to this track repo (such as changing the snippet) can we expect to see the change in the v2 website?

**Comment by verdammelt** [comment]
Merged in changes for the todo lists. But will leave this issue open until I can verify things such as the snippet.

**Comment by kytrinyx** [comment]
> how soon after making a change to this track repo (such as changing the snippet) can we expect to see the change in the v2 website?

It's supposed to be nearly immediate--we've got webhooks listening. I do know we had a bug in the update code, and then we had trouble deploying :/ I'm going to see if we can get a fresh data dump run and a fresh deploy to master this week.
