### ISSUE TITLE
Exercism Help link is non intuitive 

### ISSUE THREAD

**Issue by kevinjfoley** [exercism/common-lisp#243]
The "Excercism Help" link in the [`hello-world` exercise](https://github.com/exercism/common-lisp/blob/master/exercises/hello-world/README.md) isn't very helpful.  It links back to the main track page where it isn't clear that the help is contained in the guides side bar.  I imagine most users will have to scroll down to even see that side bar.

Thoughts on changing it to something like: 
> Check out [Installing Common Lisp](https://exercism.io/tracks/common-lisp/installation) for instructions to get started or take a look at the guides available in the "Still Stuck?" side bar.

**Comment by verdammelt** [comment]
Thanks for this feedback. I'll see about changing that wording.

**Comment by verdammelt** [comment]
@kevinjfoley if you have a moment - what do you think about the wording in PR #244 ?

**Comment by kevinjfoley** [comment]
Thanks for the update, that wording sounds much better to me
