### ISSUE TITLE
Recruiting additional maintainers for Common Lisp

### ISSUE THREAD

**Issue by kytrinyx** [exercism/common-lisp#268]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by verdammelt** [comment]
I am interested in trying to update the track for this new v3 world. I will likely have time to do this along with current mentoring duties (maintenance duties are low...)

**Comment by fedandr** [comment]
Hello! I would like to help with the Common Lisp track at Exercism. My handle is "fedandr". I am exploring Common Lisp with delight while at the same time designing (and running) an introductory course in Problem Solving for schoolkids incorporating Common Lisp. Here are the announcements:
[https://www.linkedin.com/feed/update/urn:li:activity:6615140937108598784/](url)
[https://www.facebook.com/fedandr/posts/1036393083382526](url)
I will be really glad to join the track maintenance team. Thank you!

**Comment by verdammelt** [comment]
Welcome @fedandr!

**Comment by timmyjose** [comment]
Hello @kytrinyx et al,

> If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too.

This describes my situation perfectly! I would love to help out as much as I can.

**Comment by vipermark7** [comment]
Hi, I'm interested in being a maintainer! :)

**Comment by verdammelt** [comment]
Welcome @timmyjose  & @vipermark7  - whatever help you can give will be appreciated.

I believe the next step is that you will be contacted by @ErikSchierboom and get invited into the slack etc. If you are already exercism members I think editing the maintainers.md file in the v3 common lisp track might be a good first thing to do. Along with joining the #maintaining-common-lisp channel

**Comment by Zulu-Inuoe** [comment]
Hello all. I'd like to join to help where I can. Exercism really stuck out to me. I didn't stick through with mentoring nearly as much as I wanted to, but I believe this role will be different and I hope to be of any help I can!

**Comment by thodg** [comment]
I'd like to help with the Common Lisp track

**Comment by verdammelt** [comment]
@thodg excellent! and welcome. Do you already have access to the exercism slack? If so join the #maintaining-common-lisp track and also review the v3 docs in the repo (http://github.com/exercism/v3). Unless you are already listed in the maintainers file here in this repo the first step to is to add yourself there.

**Comment by verdammelt** [comment]
I'm going to close this - seems like we got an influx of new people.

**Comment by iHiD** [comment]
I'm going to reopen this as we still get new people coming into other tracks via this method, and we could always do with more help :)
