### ISSUE TITLE
Exercise Bob: Loads incorrect file

### ISSUE THREAD

**Issue by rabuf** [exercism/common-lisp#276]
[`bob-test.lisp`](https://github.com/exercism/common-lisp/blob/master/exercises/bob/bob-test.lisp) line 6 tries to load `example.lisp`, which, along with being a completed solution, is not in the downloaded files for the exercise. Line 5 should be uncommented, line 6 should be removed or commented out.

**Comment by verdammelt** [comment]
ooh  that's embarrassing.  Looks like I didn't undo the loading of example for my local testing. Sorry about that. I am pushing up a PR and should fix it.
