### ISSUE TITLE
Roswell always seems to be unstable - perhaps stop using it?

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#322]
As long as we have used Roswell on this project we've always run into stretches of time where it simply stops working (as it is currently). Either it fails to install or fails to install lisps.

Given that we are effectively standardizing on SBCL for tooling I am suggesting using SBCL for most CI on this repo with perhaps some extra CI tasks that use other Lisps such as ABCL.

**Comment by TheLostLambda** [comment]
I'd be in favour of moving away from Roswell as well. Though I quite like it as an idea, practically speaking, it's always been a bit of a hassle. I think that SBCL is a good default for most things, and tossing in another implementation or two in the CL should help us stick to the ANSI standard.

**Comment by verdammelt** [comment]
This issue is effectively moot now that I've removed the old CI system for testing the exercises (which was broken).

A new CI system can be discussed and worked on under #340
