### ISSUE TITLE
Practice exercises must be updated to v3 format.

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#347]
1. They must be updated to use `fiveam` rather than `lisp-unit` and in the new testing style (no more #'xlisp-test feature checking...)
1. They must conform to the [specification](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md)

## Exercises needing to be updated.

Before working on one - "claim" it then when a PR is up add that detail. Check off when PR merged.

- [ ] acronym
- [ ] all-your-base
- [ ] allergies
- [ ] anagram
- [ ] armstrong-numbers
- [ ] atbash-cipher
- [ ] beer-song
- [ ] binary
- [ ] binary-search
- [ ] bob
- [ ] collatz-conjecture
- [ ] crypto-square
- [ ] difference-of-squares
- [ ] etl
- [ ] gigasecond
- [ ] grade-school
- [ ] grains
- [ ] hamming
- [ ] hello-world (PR: #356)
- [ ] isogram
- [ ] leap
- [ ] luhn
- [ ] meetup
- [ ] nucleotide-count
- [ ] pascals-triangle
- [ ] perfect-numbers
- [ ] phone-number
- [ ] prime-factors
- [ ] raindrops
- [ ] rna-transcription
- [ ] robot-name
- [ ] robot-simulator
- [ ] roman-numerals
- [ ] scrabble-score
- [ ] sieve
- [ ] space-age
- [ ] strain
- [ ] sublist
- [ ] triangle
- [ ] trinary
- [ ] twelve-days
- [ ] two-fer
- [ ] word-count

**Comment by verdammelt** [comment]
There are 43 practice exercises to update.

We could put a big todo list here with all the exercises... or we could replace this issue with an issue per exercise.

Thoughts?

**Comment by verdammelt** [comment]
For now i'll put in a list of exercises that need updating.

**Comment by TheLostLambda** [comment]
I think that this one issue is a much cleaner approach! I like this quite a bit! Thank you for putting this together!

**Comment by verdammelt** [comment]
Reviewing issues I see that this was done - so closing.
