### ISSUE TITLE
Add (empty) stub files for exercises without directory

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/common-lisp#364]
The `config.json` file contains concept exercises for which there is no corresponding `exercises/concept/<slug>` directory. This causes our syncing process to fail. Could you add the directory for these exercises? 

An example of such an exercise is `destructuring-assignment`: https://github.com/exercism/common-lisp/blob/main/config.json#L56

Closes https://github.com/exercism/website/issues/519

**Comment by verdammelt** [comment]
We could fix this by adding stubs for these 'concept exercises' or we can remove them from `config.json`. I'm thinking just removing them - thoughts @TheLostLambda

**Comment by verdammelt** [comment]
I fixed this by removing the exercises from the list. Hopefully that will not create a *different* problem.
