### ISSUE TITLE
Simplify the V3 Test Files

### ISSUE THREAD

**Issue by TheLostLambda** [exercism/common-lisp#417]
The V3 `run-tests` function no longer needs to be used by the test-runner, only the learner. We could simplify all of the V3 tests to have the same `run-tests` function as V2 – making things consistent and simpler.

Here is the proposed replacement:

```lisp
(defun run-tests (&optional (test-or-suite 'robot-simulator-suite))
  "Provides human readable results of test run. Default to entire suite."
  (run! test-or-suite))
```

**Comment by verdammelt** [comment]
And it looks like `test-exercises` system (used in CI) also does not need it. And we don't currently have a exercise generator so no complications there.

So yes, lets simplifiy.

I will mark this as a V3 thing - IMHO It should be fixed before v3 goes live.
