### ISSUE TITLE
Standardize on `(:use #:cl)` in `defpackage` form.

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#424]
Realized when reviewing #423 that we may have some inconsistency of our defpackage forms in exercises. 

We should use `(:use #:cl)` throughout to have things be standardized.

**Comment by TheLostLambda** [comment]
Since I'm still pressed for time, but this seems like low-hanging fruit, I may knock this out now :)

**Comment by verdammelt** [comment]
Good Luck!
