### ISSUE TITLE
Standardise on either interned `:cl` or uninterned `#:cl` symbols in pacakge definitions

### ISSUE THREAD

**Issue by TheLostLambda** [exercism/common-lisp#427]
I personally find `:cl` a bit less verbose / noisy, but `#:cl` might be better practice to avoid polluting the package namespace?

We should do a bit of reading up on best-practices and then make things consistent!

**Comment by verdammelt** [comment]
Do you think this sort of cleanup should be done pre-v3 or can we do it post? I'm leaning toward pre-v3.

If you agree add the v3 label.

**Comment by TheLostLambda** [comment]
I reckon it's small enough to knock out for v3!

**Comment by TheLostLambda** [comment]
Looks like [bare symbols aren't great because they pollute the current package](https://stackoverflow.com/questions/7894548/why-are-uninterned-symbols-used-for-package-names-and-exports-in-common-lisp), but we are using keywords already, so are only adding things to the keyword package anyways (which I find quite acceptable).

It seems that [PCL says](https://gigamonkeys.com/book/programming-in-the-large-packages-and-symbols.html) that uninterned symbols really aren't something too useful for packages and seems to just use keywords? I might lean towards the same since `:cl` is less verbose than `#:cl` and we don't really have any need to keep the keyword package clean.

What do you think? If you agree, I can look into knocking this out soon :)

**Comment by verdammelt** [comment]
I waffle between `#:symbol` and `:symbol` and have just now re-read the PCL reference. I feel, at the moment ( :) ) we should just go with `:symbol` it is a little "cleaner" and the other isn't really that much more "correct".

**Comment by TheLostLambda** [comment]
Cool!  I can knock this out tomorrow then when I'm reviewing the Array exercise!

**Comment by verdammelt** [comment]
OK, i'll leave it to you - was going to do it myself - but don't want to leave you with nothing to do :).

But review the Array exercise first!

**Comment by wobh** [comment]
Chiming in to share this link, see the "defpackage" section for explanation on why some prefer using uninterned symbol: https://courses.cs.northwestern.edu/325/readings/packages.php

**Comment by verdammelt** [comment]
I think that same argument is given in the footnote in PCL as well. Not sure if I'm swayed by the argument that it says storing the symbol in two places... not so worried about the small amount of memory that may save :)

**Comment by TheLostLambda** [comment]
That's certainly a helpful link to have, but I agree that I'm not convinced it's significantly better than using the keyword package. I might still standardize to `:cl`, but also carry this extra bit of knowledge forward with me!

**Comment by verdammelt** [comment]
I agree we should still standardize on `:cl` and also standardize of `:symbol` rather than `#:symbol`.
