### ISSUE TITLE
Extract track-specific help instructions from `config/exercise_readme.go.tmpl`

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/common-lisp#428]
Each track needs a file that contains track-specific instructions on how to get help. The contents of this document are only presented to the student when using the CLI. This file lives at `exercises/shared/.docs/help.md`. **You almost certainly already have this information, but need to move it to the correct place.**

For v2 tracks, this information was (usually) included in the readme template found at `config/exercise_readme.go.tmpl`. As such, tracks can extract the help instructions from the `config/exercise_readme.go.tmpl` file to the `exercises/shared/.docs/help.md` file.

See https://github.com/exercism/csharp/pull/1557/files for an example PR.

# Tracking

https://github.com/exercism/v3-launch/issues/50

**Comment by verdammelt** [comment]
@ErikShierboom - can you give myself @TheLostLambda some guidance on linking from this help.md file to other track documentation?  In the v2 doc we had links, for example pointing to our installation guide at (https://exercism.io/tracks/common-lisp/installation) which in v3 is at (https://exercism.lol/docs/tracks/common-lisp/installation).

Would you suggest retaining links like this or to include that installation guide (or a subset of it) in the help.md file directly?

**Comment by ErikSchierboom** [comment]
Personally, I would lean towards linking to the installation guide and not including it in the help.md file directly, as the help.md file's contents will be included in every exercise's HELP.md file and is probably only really useful once.
