### ISSUE TITLE
List concept exercise: nconc vs. append

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#476]
Quoting @alvaro121 in #475:

> Also, in the Bigger lists out of smaller lists section, it says:
> 
> Leslie realized they accidentally made two shopping lists not one! Write a function called list-append which adds all the items from the second list provided to the end of the first list.
> I assume the intended solution would be to use append and not nconc, but that would not add the items to the list but instead return a new list.

I suggest we correct the story text to not imply mutating the list and add a mention of nconc to the about.md for the list concept.

**Comment by alvaro121** [comment]
Is there a _mutation_ concept or similar? I could only find #318 that was closed. The would-be concept seems to be referenced at the [hash table concept](https://github.com/exercism/common-lisp/blob/c5eee935a3c8490257b5ca4a8e5c0c3375001d78/concepts/hash-tables/introduction.md):
> The use of `setf` will be explained in another concept.

**Comment by verdammelt** [comment]
This is currently no mutation concept. The `setf` concept is going to be an interesting one - perhaps several conepts, as there is first simple variable assignment, then the topic of "places" and then discussion of the 3(or more) ways to define a `setf` function.
