### ISSUE TITLE
This repo's 'about' is incorrect

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#477]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/365425/132096977-c8443e31-3f0c-4c01-87fa-ecfe1a9b9ec4.png">

The link is wrong and needs updating. 

But I can't find where to update it? Maybe I don't have the permissions to do so?

@iHiD / @ErikSchierboom sorry to bother you but unless I'm missing something I can't fix this myself

**Comment by ErikSchierboom** [comment]
Good catch. We'll update this soon-ish.

**Comment by ErikSchierboom** [comment]
Fixed for all tracks! Thanks for reporting.
