### ISSUE TITLE
Wrong instructions

### ISSUE THREAD

**Issue by DaniruKun** [exercism/common-lisp#539]
In https://github.com/exercism/common-lisp/blob/main/exercises/practice/etl/.docs/instructions.md?plain=1#L28 , it is mentioned that the transformed resulting data should have lower cased character keys, but the test cases all require them to be upper case.

Either the instructions, or the test case are wrong and should be updated.

**Comment by verdammelt** [comment]
Glad you saw this. The instructions and test cases for practice exercises come from the problem-specifications repo so that means that this is a problem of the tests in the common lisp track rather than a problem of the instructions.

Should be pretty easy to fix.

**Comment by DaniruKun** [comment]
Thank you!
