### ISSUE TITLE
 <p dir="auto">Okay, I've looked up other Common Lisp flattening algorithms, and they're all pretty involved (if wildly varying by method).  I've found flattening with loops, with recursion, with both, with overloaded methods, and even some cursed-looking algorithm which converted the input to a string, then removed the parentheses, before finally converting the string back into a list.</p>


### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#639]
> <p dir="auto">Okay, I've looked up other Common Lisp flattening algorithms, and they're all pretty involved (if wildly varying by method).  I've found flattening with loops, with recursion, with both, with overloaded methods, and even some cursed-looking algorithm which converted the input to a string, then removed the parentheses, before finally converting the string back into a list.</p>

Below is my attempt at this exercise. While my `apply append` idea would not work as you pointed out I think this is pretty simple. (It does ignore the issue of circular lists but I don't think that is something we need to handle for this exercise...)

```
(defun flatten (nested)
  (remove nil
          (reduce #'(lambda (acc item)
                      (append acc (if (atom item) (list item) (flatten item))))
                  nested :initial-value (list))))
```

_Originally posted by @PaulT89 in https://github.com/exercism/common-lisp/issues/617#issuecomment-1134301003_

**Comment by verdammelt** [comment]
WTF happened here?!

(using emacs' `code-review` package and things went weird :) )

**Comment by ErikSchierboom** [comment]
@verdammelt I've renamed as this is breaking something in our website :D

**Comment by PaulT89** [comment]
I don't know - the tests worked fine for me (at least when I tested it before the merge), and I just did the test on the Exercism website, and they worked there.  I'm not using emacs though, so maybe it's an emacs-specific thing?

**Comment by verdammelt** [comment]
@ErikSchierboom  Did the title of the issue cause a problem? 

1. I didn't mean to create the issue at all - so unlikely to happen again
2. Was created by an emacs package called `code-review` - but just using GitHub API so likely other tools/users could create such issue titles.

What was the problem? Was it the length of the HTML `p` tag?
