### ISSUE TITLE
Individual students' "solutions" display on exercism.org not working for Common Lisp

### ISSUE THREAD

**Issue by eigenhombre** [exercism/common-lisp#647]
Not sure if this belongs here or in some other repo...

https://exercism.org/profiles/eigenhombre/solutions?track_slug=common-lisp shows no completed exercises (there should be 24), but
https://exercism.org/profiles/eigenhombre/solutions?track_slug=python shows several.

This is on Firefox 100.0.2 on MacOS 11.6.4.

**Comment by verdammelt** [comment]
That is very odd. I will find the correct place for you to file an issue as this repository is only for things like the exercises and test runners - not for anything directly to do with the web site itself.

**Comment by verdammelt** [comment]
I have checked and you should open an issue on the `exercism` repository: https://github.com/exercism/exercism/issues

Thanks and good luck.

**Comment by eigenhombre** [comment]
@verdammelt : Thank you!

https://github.com/exercism/exercism/issues/6398 is the new issue.
