### ISSUE TITLE
Typo in Pizza Pi tooltip

### ISSUE THREAD

**Issue by BNAndras** [exercism/common-lisp#672]
Integers is misspelled as intergers on the tooltip for Pizza Pi on the syllabus.
![image](https://user-images.githubusercontent.com/20251272/196018432-61204691-b576-43c7-aace-7359fa0fce8a.png)

**Comment by verdammelt** [comment]
Ah, good catch. I'll try to update that soon. Feel free to make a PR yourself if you want.

**Comment by SleeplessByte** [comment]
Closed by #673
