### ISSUE TITLE
Broken resources URL

### ISSUE THREAD

**Issue by BNAndras** [exercism/common-lisp#682]
On the track's [resources page](https://exercism.org/docs/tracks/common-lisp/resources), there's currently a broken link for [The Common Lisp Wiki](http://www.cliki.net/). I did some brief googling, and I wasn't able to identify whether this was a temporary outage or not. Google last cached the site two days ago.

**Comment by verdammelt** [comment]
Cliki did seem to be down yesterday - but is back today. So I'm going to close this for now - I think the link is still valid to keep on our Resources page.
