### ISSUE TITLE
socks-and-sexprs exercise: stub file needs more guidance for lisp newbies

### ISSUE THREAD

**Issue by glennj** [exercism/common-lisp#683]
As a newbie, I was having tremendous difficulty with the very first task on this exercise until I finally figured out where to put the symbol

```lisp
;; Evaluates to some symbol (not a keyword)
(defun lennys-favorite-food ())
```
Looking at that with newcomer eyes, where is the symbol supposed to go? Inside the empty parens is the most "obvious" place.

I had to reread the About Expressions text a few times before I realized the empty parens are the argument list.

I think
* the Expressions doc needs more guidance about `defun` 
* the stub file could add helpful comments:
  ```lisp
  ;; Evaluates to some symbol (not a keyword)
  (defun lennys-favorite-food ()
    ; your symbol goes here
  )
  ```

**Comment by verdammelt** [comment]
Thank you for the feedback on this exercise.

This exercise is not intended to teach about `defun` that is done in "Lilly's Lasagna" (the text of the introduction to functions concept can be found here (https://github.com/exercism/common-lisp/blob/main/concepts/functions/introduction.md).

I do like the comment explaining where to put your answer (on the first such function) which will give the student just a little guidance... I'll have a PR up for that shortly.

I'd like to know your opinion on the description of the functions concept in the later exercise (linked above) if you have the time. Feel free to open a new issue if you have comments/problems with it.
