### ISSUE TITLE
Typo in robot-simulator test.

### ISSUE THREAD

**Issue by JKilgallen** [exercism/common-lisp#762]
Sorry if opening an issue for this is unnecessary (this is my first time ever opening one). 

I noticed a couple of typos in the robot-simulator test suite. 
In line 102 of robot-simulator-test.lisp it reads 
`advance-decrements-y-when-facing-north` 
when I believe it should be (based on the test)
`advance-decrements-y-when-facing-south`
Additionally, line 126 reads
`move-east-and-north-readme`
when I think it should just be 
`move-east-and-north`
in line with the rest of the tests.

Would anyone mind if I made the changes and did a pull request? (my first on an open-source project)

**Comment by verdammelt** [comment]
@JKilgallen Thanks for catching these.

Do you want to submit a PR?
