### ISSUE TITLE
Implement `leap`?

### ISSUE THREAD

**Issue by BNAndras** [exercism/common-lisp#776]
[Leap will be featured on Exercism for #48in24 starting on January 16th](https://forum.exercism.org/t/48in24-exercise-01-16-leap/8964/2). I can port this exercise this weekend and start working on bottle-song as previously discussed.

**Comment by verdammelt** [comment]
The `leap` exercise is already implemented (maybe one of the first exercises actually).

Or is there  some additional work that needs to be done?

**Comment by BNAndras** [comment]
Huh, that’s odd. It did seem weird this was the only track that didn’t implement it yet. I’ll make a note of it in that thread.

**Comment by verdammelt** [comment]
@BNAndras 
Is there anything special that does need to be done? Or is simply having the exercise sufficient for this new event?

**Comment by BNAndras** [comment]
Ideally we’d have the exercise implemented and maybe approaches written, but just the exercise is enough.

**Comment by verdammelt** [comment]
I guess there is nothing to do here then. So I will close this issue.
