### ISSUE TITLE
key-comparison maze of arrays unclear test of identity or internal structure

### ISSUE THREAD

**Issue by driftsignal** [exercism/common-lisp#798]
the equality test for maze of arrays appears to test for identity.

[key-comparison-test.lisp] line 115-118:

        (:room-arrays
          . (((,+an-array+ ,+a-similar-but-different-array+) . explosion)
          ((,+an-array+ ,+an-array+) . victory)))

the [readme] suggests internal comparison:

> ## 6. The maze of arrays
> 
> This maze is simpler with only two rooms. The first needs a key that checks if the arrays contain the equal contents. The second needs a key that is more flexible about checking equality of numbers.
> 
> For example:
> 
> ```lisp
> a                        ; => #[13 23]
> b                        ; => #[13 23.0]
>
> (key-arrays a b)         ; => NIL
> (key-arrays-loosely a b) ; => T
> ```
> 
> because a permissive equality predicate will not consider numeric type when comparing the contents of an array.

would it make sense for the readme or the tests be updated to mirror each other?

    

[key-comparison-test.lisp]: https://github.com/exercism/common-lisp/blob/main/exercises/concept/key-comparison/key-comparison-test.lisp
[readme]: https://github.com/exercism/common-lisp/blob/main/exercises/concept/key-comparison/.docs/instructions.md

**Comment by verdammelt** [comment]
Thanks for reporting this - I will check it out.

**Comment by verdammelt** [comment]
@driftsignal I updated the test data and instructions to hopefully remove the possible confusion. Please review #803 and let me know if you think it corrects this problem.
